// <auto-generated />
using APITask.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APITask.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APITask.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CatName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CatOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CatName")
                        .HasDatabaseName("IX_Categories_CatName");

                    b.ToTable("Categories", "MasterSchema");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CatName = "Fiction",
                            CatOrder = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CatName = "Science",
                            CatOrder = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CatName = "Technology",
                            CatOrder = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CatName = "Biography",
                            CatOrder = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CatName = "History",
                            CatOrder = 5,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("APITask.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("BookPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BookPrice");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", "MasterSchema");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "John Smith",
                            BookPrice = 29.99m,
                            CategoryId = 1,
                            Description = "An exciting fiction novel",
                            IsDeleted = false,
                            Title = "The Great Adventure"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Dr. Sarah Wilson",
                            BookPrice = 45.50m,
                            CategoryId = 2,
                            Description = "Basic principles of physics",
                            IsDeleted = false,
                            Title = "Physics Fundamentals"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Mike Johnson",
                            BookPrice = 55.00m,
                            CategoryId = 3,
                            Description = "Complete guide to web technologies",
                            IsDeleted = false,
                            Title = "Modern Web Development"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Walter Isaacson",
                            BookPrice = 35.99m,
                            CategoryId = 4,
                            Description = "Life story of Apple founder",
                            IsDeleted = false,
                            Title = "Steve Jobs Biography"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Robert Miller",
                            BookPrice = 42.75m,
                            CategoryId = 5,
                            Description = "Comprehensive history of WWII",
                            IsDeleted = false,
                            Title = "World War II Chronicles"
                        });
                });

            modelBuilder.Entity("APITask.Models.Entities.Product", b =>
                {
                    b.HasOne("APITask.Models.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("APITask.Models.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
